#!/bin/sh /etc/rc.common

START=81
STOP=29
USE_PROCD=1

PROG=/usr/sbin/ap-isolation-fdb

start_service() {
	. /lib/functions.sh
	config_load ap-isolation
	config_get_bool wu settings fdb_workaround 0
	[ "$wu" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	"$PROG" cleanup
}

service_triggers() {
	procd_add_reload_trigger "ap-isolation"
}

reload_service() {
	stop
	start
}
