#!/bin/sh /etc/rc.common

START=80
STOP=30
USE_PROCD=1

PROG=/usr/sbin/ap-isolation.sh

start_service() {
	$PROG start
	return 0
}

stop_service() {
	$PROG stop
	return 0
}

reload_service() {
	$PROG reload
	return 0
}

service_triggers() {
	procd_add_reload_trigger "wireless"
	procd_add_reload_trigger "ap-isolation"
}
